from distutils.core import setup

setup(name='recepies',
      version='1.0',
      description='Book recepie web app',
      author='Gabriel Fr. Borges de Carvalho',
      author_email='gabrielfr.borges@gmail.com',
      python_requires='>=3.8.6',
      install_requires=[
          "attrs==20.3.0",
          "blinker==1.4",
          "click==7.1.2",
          "coverage==5.5",
          "Flask==1.1.2",
          "Flask-Injector==0.12.3",
          "greenlet==1.0.0",
          "gunicorn==20.0.4",
          "iniconfig==1.1.1",
          "injector==0.18.4",
          "itsdangerous==1.1.0",
          "Jinja2==2.11.3",
          "MarkupSafe==1.1.1",
          "packaging==20.9",
          "pluggy==0.13.1",
          "psycopg2==2.8.6",
          "py==1.10.0",
          "pyparsing==2.4.7",
          "pytest==6.2.2",
          "python-dotenv==0.17.0",
          "SQLAlchemy==1.4.6",
          "toml==0.10.2",
          "typing-extensions==3.7.4.3",
          "Werkzeug==1.0.1",
          "Flask-Migrate",
          "Flask-SQLAlchemy",
          "Flask-Script",
          "mysqlclient",
      ])
